[build.env]
passthrough = [
    "PKG_CONFIG_PATH",
    "PKG_CONFIG_LIBDIR", 
    "PKG_CONFIG_ALLOW_CROSS",
    "PKG_CONFIG_SYSROOT_DIR",
    "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS"
]

[target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile.aarch64"